### ISSUE TITLE
Can berrybrew run inside docker containers? (Perl instances within network shares)

### ISSUE THREAD

**Issue by versionaire** [stevieb9/berrybrew#301] opened 2021-07-28 16:15 UTC
Hello,

This is not an issue but a question. Are you aware if berrybrew will work inside docker containers and if so are there any major issues? 

I work in a large perl shop and we are migrating much of our workload to docker automation. We would like to spin up containers and use berrybrew to access perl mounted versions from a local resource. In this manner we could have static perls with pre-installed modules. Currently our overseas development team spins up an image, installs perl and then begins installing various modules. For each instance.  We had thought berrybrew might be a solution to get around these bottlenecks.

**Comment by stevieb9** [comment] 2021-07-28 21:55
I have never tried it, but I can't see that it wouldn't work.

If I understand correctly, you want to mount a local or network drive into
a docker container, and have berrybrew operate Perl instances that are
located on that shared drive?

I assume that you'd preconfigure berrybrew to point to the right place
initially, and if you upgrade perls in the future, you'd update the base
image?

If you can confirm, I'll gladly do some initial testing, and if it doesn't
work, make it so that it does.

**Comment by versionaire** [comment] 2021-07-29 15:04
That is exactly what we'd like to do. In our container we have SMB (windows) mounted shares and each container instance installs Perl and then a list of modules. Our team is assembling a different set of modules for each job we have (and we have maybe 1500) and in production we have a static Perl (with all the modules needed already installed). Production Perl changes rarely. Berrybrew looks perfect because we could start the container and berrybrew the correct version. I'm going to attempt to containerize berrybrew and will come back shortly with how we made out in our efforts. Thank you stevieb9 for quick response.

**Comment by stevieb9** [comment] 2021-07-29 16:13
Let me know if you have any problems, and I'll work on the issue promptly.
If you've got a method in which I could work within your actual environment
to make any changes, that would be extremely beneficial, as it's been some
time since I've done anything with containers etc.

**Comment by versionaire** [comment] 2021-07-29 19:10
I'm attempt to build a Perl outside the container that I can access inside. I've installed berrybrew and used the default top level directory (c:\berrybrew) for my Perl versions. I added a half dozen modules and then zipped that folder up, copied and then unzipped to a samba file share.  and renamed the original top level directory. I do this because installing as admin means share rights are dropped (or changed). My mapped share I can see, I can run perl and use a module from that folder. But I cannot berrybrew register the folder. I get installation directory 't:\path\container_perls' does not exist. When I run the register command a c:\berrybrew is created. So I put the original folder back in place and still I can run dir on the t: folder but cannot register the directory.

**Comment by stevieb9** [comment] 2021-07-29 19:59
OK. It sounds like the register process isn't able to see network share
directories. I'll set up a similar situation here (mount a shared Samba
drive) and see what I can come up with.

**Comment by stevieb9** [comment] 2021-07-29 20:04
What version of berrybrew are you running (berrybrew version)?

**Comment by versionaire** [comment] 2021-07-29 20:45
I should have tried the unc path too (\\server\path) to be thorough. I'm running 1.34.

**Comment by stevieb9** [comment] 2021-07-31 01:49
Can you please run `berrybrew options` and paste me the results of that command?

**Comment by versionaire** [comment] 2021-08-01 17:59
Steve, options output below. Since I could not install to a samba share (referenced by drive letter) I installed to the c: drive and then moved the folder which I then could not register (maybe I could have modified the registry). I want to build a berrybrew on a share , add modules, and then access the berrybrewed perl on that share from a docker container. As I understand from our developers berrybrew would have to be installed without a GUI. I read it's possible but not the way they are building our jobs.  So I'd thought unzip and try regedit commands. I am very grateful for your efforts here. Thanks again.

Option configuration:

        debug:             false
        root_dir:          C:\berrybrew
        temp_dir:          C:\berrybrew\temp
        download_url:      https://strawberryperl.com/releases.json
        windows_homedir:   false
        custom_exec:       false
        run_mode:          prod
        file_assoc:        Perl_program_file
        file_assoc_old:
        warn_orphans:      false

**Comment by stevieb9** [comment] 2021-08-02 14:28
I do think the only step you missed was updating the registry. I reproduced
the problem:

- Install berrybrew
- Install a Perl
- Move Perl to \\scelia\shared\berrybrew
- Try to switch to the newly installed Perl, failed

Fix:

- berrybrew options root_dir \\scelia\shared\berrybrew
- Restart terminal window
- berrybrew switch installed Perl
- works!

Now, using the graphical installer, this is even simpler:

- Run the installer
- Leave "Destination Folder" default for installation directory, or change
it if necessary
- For "Destination Folder" for Perl instances, select
\\scelia\shared\berrybrew (create the folder in advance)
- Uncheck "Run UI at startup"
- Done!

Here's what my options look like now:

c:\repos\berrybrew>berrybrew options

Option configuration:

        debug:             false
        root_dir:          \\scelia\shared\berrybrew
        temp_dir:          \\scelia\shared\berrybrew\temp
        download_url:      https://strawberryperl.com/releases.json
        windows_homedir:   false
        custom_exec:       false
        run_mode:          prod
        file_assoc:
        file_assoc_old:
        warn_orphans:      false

If the base container has berrybrew set up this way, things should just
work. If you add a new perl and want to switch to it and use it by default,
the base container will have to be updated as such.

Let me know if this helps!

**Comment by stevieb9** [comment] 2021-10-08 15:09
This seems to work properly following the correct techniques. Closing as resolved.

**Closed as completed by stevieb9** 2021-10-08 15:09 UTC
